name = "abdulhanif"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[build]
command = "cd web && npm install && npm run build"
